# Generated by Django 2.2 on 2020-10-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthRefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OAuthScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('code', models.CharField(max_length=40, unique=True)),
                ('redirect_uri', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.OAuthClient')),
                ('scopes', models.ManyToManyField(to='tokens.OAuthScope')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credentials.OAuthUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('access_token', models.CharField(max_length=40, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.OAuthClient')),
                ('refresh_token', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='tokens.OAuthRefreshToken')),
                ('scopes', models.ManyToManyField(to='tokens.OAuthScope')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credentials.OAuthUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
