# Generated by Django 3.0.7 on 2020-07-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferry_plot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
