# Generated by Django 2.2 on 2020-10-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferry_plot', '0002_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSeries',
        ),
        migrations.RemoveField(
            model_name='download',
            name='Status',
        ),
    ]
