# Generated by Django 3.1.1 on 2025-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferry_plot', '0003_auto_20201002_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='sens',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
