# Generated by Django 3.2.25 on 2025-03-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferry_plot', '0004_auto_20250227_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='id',
            new_name='id_meta',
        ),
    ]
